### ISSUE TITLE
a class name cause crash

### ISSUE THREAD

**Issue by haoboxuxu** [shial4/SpriteKit-SwiftUI-Template#1]
nice project, but it crash every time  when I  change the class name GameScene in "GameScene.swift"

**Comment by shial4** [comment]
You will have to change custom class name in your game scene file (.sks)

**Comment by shial4** [comment]
Take a look here
https://github.com/shial4/SpriteKit-SwiftUI-Template/commit/ece8dc7f20387b5fce4e0020e9227ac7b89d653d

I created branched and did change name with even the scene file name. 
Hope that will help you see all the places to change :) 

Let me know @haoboxuxu 

Cheers,
Szymon

**Comment by haoboxuxu** [comment]
thanks a lot bro!!!!

**Comment by shial4** [comment]
Enjoy 😊
